<?php
include "header.php";
?>

<html>

<body>
    <section id="team" class="team">
        <div class="container">

            <div class="section-title">
                <h2 style="color:black">Our Team</h2>
            </div>

            <div class="rows">

                <div class="col-lg-3 col-md-6 d-flex align-items-stretch">
                    <div class="member">
                        <div class="member-img">
                            <img src="img/lh1.jpg" class="img-fluid" alt="">
                            <div class="social">
                                <!-- <a href="#"><i class="bi bi-twitter"></i></a> -->
                                <!-- <a href="https://www.facebook.com/profile.php?id=100076435967272"><i 
                                        class="bi bi-facebook"></i></a>                 -->
                                <a href="https://www.instagram.com/deeppatel1355/"><i class="bi bi-instagram"></i></a>
                                <a href="https://www.linkedin.com/in/deep-patel-538114263/"><i
                                        class="bi bi-linkedin"></i></a>
                            </div>
                        </div>
                        <div class="member-info">
                            <h4>Deep Patel</h4>
                            <span>Developer</span>
                        </div>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6 d-flex align-items-stretch">
                    <div class="member">
                        <div class="member-img">
                            <img src="img/lh1.jpg" class="img-fluid" alt="">
                            <div class="social">
                                <!-- <a href="#"><i class="bi bi-twitter"></i></a> -->
                                <!-- <a href="https://www.facebook.com/denis.ruparel/"><i class="bi bi-facebook"></i></a> -->
                                <a href="https://www.instagram.com/_itsmekashish_28/"><i
                                        class="bi bi-instagram"></i></a>
                                <!-- <a href="https://www.linkedin.com/in/denis-ruparel-249539243/"><i class="bi bi-linkedin"></i></a> -->
                            </div>
                        </div>
                        <div class="member-info">
                            <h4>Kashish Jansari</h4>
                            <span>Developer</span>
                        </div>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6 d-flex align-items-stretch">
                    <div class="member">
                        <div class="member-img">
                            <img src="img/lh1.jpg" class="img-fluid" alt="">
                            <div class="social">
                                <!-- <a href="#"><i class="bi bi-twitter"></i></a> -->
                                <!-- <a href="https://www.facebook.com/denis.ruparel/"><i class="bi bi-facebook"></i></a> -->
                                <a href="https://www.instagram.com/jeel_4704/"><i
                                        class="bi bi-instagram"></i></a>
                                <!-- <a href="https://www.linkedin.com/in/denis-ruparel-249539243/"><i class="bi bi-linkedin"></i></a> -->
                            </div>
                        </div>
                        <div class="member-info">
                            <h4>Jeel Patel</h4>
                            <span>Developer</span>
                        </div>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6 d-flex align-items-stretch">
                    <div class="member">
                        <div class="member-img">
                            <img src="img/lh1.jpg" class="img-fluid" alt="">
                            <div class="social">
                                <!-- <a href=""><i class="bi bi-twitter"></i></a>-->
                                <!-- <a href="https://www.facebook.com/profile.php?id=100028756912083"><i 
                                        class="bi bi-facebook"></i></a>  -->
                                <a href="https://www.instagram.com/rastha_2903/"><i class="bi bi-instagram"></i></a>
                                <!-- <a href=""><i class="bi bi-linkedin"></i></a> -->
                            </div>
                        </div>
                        <div class="member-info">
                            <h4>Astha Patel</h4>
                            <span>Developer</span>
                        </div>
                    </div>
                </div>


            </div>

        </div>
    </section>
</body>

</html>