<?php
include "header.php";
?>

<html>

<body>
    <h2>Indian Heritage Gallery</h2>

    <!-- <h4>Resize the browser window to see the effect.</h4> -->

    <div class="responsive">
        <div class="gallery">
            <a target="_blank" href="img_5terre.jpg">
                <img src="img/h2.jpeg" alt="Cinque Terre" width="600" height="400">
            </a>
            <div class="desc"> Gujarat</div>
        </div>
    </div>


    <div class="responsive">
        <div class="gallery">
            <a target="_blank" href="img_forest.jpg">
                <img src="img/h3.jpeg" alt="Forest" width="600" height="400">
            </a>
            <div class="desc"> Gujarat</div>
        </div>
    </div>

    <div class="responsive">
        <div class="gallery">
            <a target="_blank" href="img_lights.jpg">
                <img src="img/h4.jpeg" alt="Northern Lights" width="600" height="400">
            </a>
            <div class="desc"> Gujarat</div>
        </div>
    </div>

    <div class="responsive">
        <div class="gallery">
            <a target="_blank" href="img_mountains.jpg">
                <img src="img/lh1.jpg" alt="Mountains" width="600" height="400">
            </a>
            <div class="desc"> Gujarat</div>
        </div>
    </div>

    <div class="clearfix"></div>

    <div style="padding:6px;">

    </div>

</body>

</html>